name: likemostanyone
favicon: null
layout_spectrum: 0.40972
typography_spectrum: 0.1764632617123425
title: Like Most Anyone
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#aeaeae'
    - '#c8c8c8'
    - '#080808'
    - '#747474'
    - '#4f4f4f'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
